[build]
  # The directory containing the deployable application files
  publish = "dist" 
  # The command Netlify runs to build the project
  command = "npm run build"

[build.environment]
  # Pinning Node version to a specific, stable LTS release (v22) to satisfy Vite's dependency requirements (v22.12+).
  NODE_VERSION = "22.12.2"