[build]
  # The directory containing the deployable application files
  publish = "dist" 
  # The command Netlify runs to build the project
  command = "npm run build"

[build.environment]
  # Pinning Node version to the major LTS release (v20) to ensure Netlify finds a compatible version.
  NODE_VERSION = "20"