[build]
  # The directory containing the deployable application files
  publish = "dist" 
  # The command Netlify runs to build the project
  command = "npm run build"

[build.environment]
  # Pinning Node version 20 to satisfy Vite's dependency requirements (v20.19+)
  # This fixes the final environment compatibility error.
  NODE_VERSION = "20"